rm(list = ls(all.names = TRUE))
library(readxl)
library(class)
library(tidyverse)
library(caret)
install.packages("factoextra")
library(factoextra)
install.packages("cluster")
library(cluster)
install.packages("scorecard")
library(scorecard)
library(dplyr)
require(caTools)
churn_clean <- read.csv("C:/Users/ContactTracer/Desktop/D212 Data Mining II Task 1/churn_clean.csv")
churn_clean_new <- churn_clean %>% select(15, 16, 17, 20, 21, 24, 40, 41, 42)
str(churn_clean_new)
churn_clean_new$Churn <- as.numeric(as.factor(churn_clean_new$Churn))
churn_data <-churn_clean_new[,4]
churn_clean_new <- churn_clean_new[-4]
churn_clean_scaled <- scale(churn_clean_new)
churn_clean_final <- cbind(churn_clean_scaled, new_col = churn_data)
fviz_nbclust(churn_clean_final, kmeans, method = "wss")
km <- kmeans(churn_clean_final, centers = 2, nstart = 25)
km
split1=sample.split(churn_clean_final[4,],SplitRatio=2/3)
train=subset(churn_clean_final,split1==TRUE)
test=subset(churn_clean_final,split1==FALSE)
kmtrain <- kmeans(train, centers = 2, nstart = 25)
kmtrain
kmtest<- kmeans(test, centers = 2, nstart = 25)
kmtest
predicted_value <- c(1.467066, 1.060132)
expected_value <- c(1.476877, 1.054540)
str(predicted_value)
str(expected_value)
expected_value <- as.factor(expected_value)
str(expected_value)
predicted_value <- as.factor(predicted_value)
str(predicted_value)
example <- confusionMatrix(data=predicted_value, reference = expected_value)
acc <- abs(predicted_value - expected_value)*100
mean(acc)
mydata.cor = cor(churn_clean_final)
mydata.cor
install.packages("corrplot")
library(corrplot)
corrplot(mydata.cor)
